// Code generated by mockery (devel). DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ArgumentParser is an autogenerated mock type for the ArgumentParser type
type ArgumentParser struct {
	mock.Mock
}

// OptionString provides a mock function with given fields: name, value
func (_m *ArgumentParser) OptionString(name string, value string) *string {
	ret := _m.Called(name, value)

	var r0 *string
	if rf, ok := ret.Get(0).(func(string, string) *string); ok {
		r0 = rf(name, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	return r0
}

// Parse provides a mock function with given fields:
func (_m *ArgumentParser) Parse() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PositionalArguments provides a mock function with given fields:
func (_m *ArgumentParser) PositionalArguments() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}
