// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	services "github.com/jimenezmaximiliano/migrations/services"
	mock "github.com/stretchr/testify/mock"
)

// CommandArgument is an autogenerated mock type for the CommandArgument type
type CommandArgument struct {
	mock.Mock
}

// ParseAndValidate provides a mock function with given fields:
func (_m *CommandArgument) ParseAndValidate() (services.Arguments, bool) {
	ret := _m.Called()

	var r0 services.Arguments
	if rf, ok := ret.Get(0).(func() services.Arguments); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(services.Arguments)
	}

	var r1 bool
	if rf, ok := ret.Get(1).(func() bool); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}
