// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	models "github.com/jimenezmaximiliano/migrations/models"
	mock "github.com/stretchr/testify/mock"
)

// Display is an autogenerated mock type for the Display type
type Display struct {
	mock.Mock
}

// DisplayError provides a mock function with given fields: err
func (_m *Display) DisplayError(err error) {
	_m.Called(err)
}

// DisplayErrorWithMessage provides a mock function with given fields: err, message
func (_m *Display) DisplayErrorWithMessage(err error, message string) {
	_m.Called(err, message)
}

// DisplayGeneralError provides a mock function with given fields: err
func (_m *Display) DisplayGeneralError(err error) {
	_m.Called(err)
}

// DisplayHelp provides a mock function with given fields:
func (_m *Display) DisplayHelp() {
	_m.Called()
}

// DisplayRunMigrations provides a mock function with given fields: migrations
func (_m *Display) DisplayRunMigrations(migrations models.Collection) {
	_m.Called(migrations)
}

// DisplaySetupError provides a mock function with given fields: err
func (_m *Display) DisplaySetupError(err error) {
	_m.Called(err)
}
