// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import (
	models "github.com/jimenezmaximiliano/migrations/models"
	mock "github.com/stretchr/testify/mock"
)

// Fetcher is an autogenerated mock type for the Fetcher type
type Fetcher struct {
	mock.Mock
}

// GetMigrations provides a mock function with given fields: migrationsDirectoryAbsolutePath
func (_m *Fetcher) GetMigrations(migrationsDirectoryAbsolutePath string) (models.Collection, error) {
	ret := _m.Called(migrationsDirectoryAbsolutePath)

	var r0 models.Collection
	if rf, ok := ret.Get(0).(func(string) models.Collection); ok {
		r0 = rf(migrationsDirectoryAbsolutePath)
	} else {
		r0 = ret.Get(0).(models.Collection)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(migrationsDirectoryAbsolutePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
