// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// OptionParser is an autogenerated mock type for the OptionParser type
type OptionParser struct {
	mock.Mock
}

// Parse provides a mock function with given fields:
func (_m *OptionParser) Parse() {
	_m.Called()
}

// String provides a mock function with given fields: name, value, usage
func (_m *OptionParser) String(name string, value string, usage string) *string {
	ret := _m.Called(name, value, usage)

	var r0 *string
	if rf, ok := ret.Get(0).(func(string, string, string) *string); ok {
		r0 = rf(name, value, usage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	return r0
}
